platform :ios, '11.0'

target 'Example' do
  use_frameworks!

  pod 'ConsolePrint', :path => '../'


  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      if ['ConsolePrint'].include? target.name
          target.build_configurations.each do |config|
              if config.name == "Debug"
                  config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] += "ConsolePrint"
              end
          end
      end
  end
end